# -*- coding: utf-8 -*-
"""Site - TotalHealth HIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKcjeyrQqCGk4PLc-stUzioqexG37as_
"""

---

### 2. `app.py` (O Código Principal Atualizado)

```python
import streamlit as st
import sqlite3
import pandas as pd
from datetime import datetime

# Configuração da página do site
st.set_page_config(
    page_title="OmniCare HIS — Painel de Gestão",
    page_icon="🏥",
    layout="wide"
)

DB_NAME = "omnicare_database.db"

def obter_conexao():
    conn = sqlite3.connect(DB_NAME)
    conn.execute("PRAGMA foreign_keys = ON;") # Ativa estritamente as chaves estrangeiras
    return conn

def inicializar_sistema():
    conn = obter_conexao()
    cursor = conn.cursor()

    # Criação das tabelas baseadas exatamente no PDF do Problema 4
    cursor.execute("CREATE TABLE IF NOT EXISTS CID10 (CAT TEXT PRIMARY KEY, Descr TEXT);")
    cursor.execute("CREATE TABLE IF NOT EXISTS TUSS (CodTUSS TEXT PRIMARY KEY, Descr TEXT, Valor REAL, ID_tiposServicos INTEGER);")
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS Pacientes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Nome TEXT, Sexo TEXT, CPF TEXT, Peso INTEGER, Altura REAL, Data_Nasc TEXT
    );""")

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS Atendimentos (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        Data_atend TEXT NOT NULL,
        CID10_CAT TEXT,
        Descr TEXT,
        Cod_Manchester TEXT,
        Pacientes_id INTEGER NOT NULL,
        FOREIGN KEY (Pacientes_id) REFERENCES Pacientes(id) ON DELETE RESTRICT,
        FOREIGN KEY (CID10_CAT) REFERENCES CID10(CAT) ON DELETE RESTRICT
    );""")

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS Servicos (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        Data_Serv TEXT NOT NULL,
        Cod_TUSS TEXT NOT NULL,
        ID_medico INTEGER,
        Atendimentos_ID INTEGER NOT NULL,
        Atendimentos_Pacientes_id INTEGER NOT NULL,
        FOREIGN KEY (Atendimentos_ID) REFERENCES Atendimentos(ID) ON DELETE RESTRICT,
        FOREIGN KEY (Cod_TUSS) REFERENCES TUSS(CodTUSS) ON DELETE RESTRICT
    );""")

    # Carga de Dados Iniciais de Teste (Mock Data)
    cursor.execute("SELECT COUNT(*) FROM Pacientes;")
    if cursor.fetchone() == 0:
        cursor.executemany("INSERT INTO Pacientes (Nome, Sexo, CPF, Peso, Altura, Data_Nasc) VALUES (?, ?, ?, ?, ?, ?);", [
            ('Ana Costa', 'F', '11122233344', 65, 1.68, '1995-03-12'),
            ('Carlos Souza', 'M', '55566677788', 82, 1.75, '1988-07-24'),
            ('Beatriz Lima', 'F', '99988877766', 58, 1.62, '2001-11-02')
        ])
        cursor.executemany("INSERT INTO CID10 VALUES (?, ?);", [
            ('R51', 'Cefaleia'), ('J11', 'Influenza (Gripe)'), ('S00', 'Traumatismo Superficial')
        ])
        cursor.executemany("INSERT INTO TUSS VALUES (?, ?, ?, ?);", [
            ('40101010', 'Consulta Emergência', 180.00, 1),
            ('40202020', 'Hemograma Completo', 45.00, 2),
            ('40303030', 'Raio-X de Tórax', 130.00, 2),
            ('50001010', 'Administração de Medicação', 25.00, 3)
        ])
        cursor.executemany("INSERT INTO Atendimentos (Data_atend, CID10_CAT, Descr, Cod_Manchester, Pacientes_id) VALUES (?, ?, ?, ?, ?);", [
            ('2026-05-19', 'R51', 'Dor de cabeça forte pulsante', 'Laranja', 1),
            ('2026-05-19', 'J11', 'Febre e dores no corpo', 'Verde', 2),
            ('2026-05-20', 'S00', 'Queda de nível', 'Amarelo', 3),
            ('2026-05-20', 'R51', 'Retorno para reavaliação', 'Verde', 1)
        ])
        cursor.executemany("INSERT INTO Servicos (Data_Serv, Cod_TUSS, ID_medico, Atendimentos_ID, Atendimentos_Pacientes_id) VALUES (?, ?, ?, ?, ?);", [
            ('2026-05-19', '40101010', 991, 1, 1),
            ('2026-05-19', '50001010', 991, 1, 1),
            ('2026-05-19', '40101010', 992, 2, 2),
            ('2026-05-19', '40202020', 992, 2, 2),
            ('2026-05-20', '40101010', 991, 3, 3),
            ('2026-05-20', '40303030', 993, 3, 3),
            ('2026-05-20', '40202020', 991, 4, 1)
        ])
        conn.commit()
    conn.close()

inicializar_system = inicializar_sistema()

# --- DESIGN DA INTERFACE WEB ---
st.title("🏥 OmniCare HIS — Gestão de Serviços Médicos")
st.markdown("Sistema Integrado de Auditoria e Validação de Indicadores Hospitalares.")

# BARRA LATERAL (SIDEBAR) - Estatísticas Globais do Hospital
with st.sidebar:
    st.header("📊 Painel Executivo")
    conn = obter_conexao()
    total_pacientes = conn.execute("SELECT COUNT(*) FROM Pacientes").fetchone()
    total_atendimentos = conn.execute("SELECT COUNT(*) FROM Atendimentos").fetchone()
    faturamento_global = conn.execute("SELECT SUM(t.Valor) FROM Servicos s JOIN TUSS t ON s.Cod_TUSS = t.CodTUSS").fetchone()
    conn.close()

    st.metric("Total de Pacientes Cadastrados", total_pacientes)
    st.metric("Atendimentos Registrados", total_atendimentos)
    st.metric("Faturamento Acumulado", f"R$ {faturamento_global:.2f}")
    st.divider()
    st.caption("Desenvolvido para o Módulo de Programação Biomédica © 2026")

# ABAS DE NAVEGAÇÃO REQUISITADAS PELO PROBLEMA
aba1, aba2, aba3, aba4, aba5 = st.tabs([
    "💰 Faturamento por Atendimento",
    "👤 Conta por Paciente",
    "🔍 Rastreamento TUSS",
    "📅 Atividade por Data",
    "🔒 Segurança de Dados"
])

# CONSULTA 1: VALOR TOTAL DE UM ATENDIMENTO ESPECÍFICO
with aba1:
    st.header("1. Valor Total de um Atendimento Específico")
    conn = obter_conexao()
    df_atend = pd.read_sql_query("""
        SELECT a.ID, a.Data_atend, p.Nome, a.Cod_Manchester
        FROM Atendimentos a JOIN Pacientes p ON a.Pacientes_id = p.id
    """, conn)
    conn.close()

    lista_atendimentos = [f"Atendimento Nº {row['ID']} - Paciente: {row['Nome']} ({row['Data_atend']})" for _, row in df_atend.iterrows()]

    if lista_atendimentos:
        selecionado = st.selectbox("Selecione o Atendimento para Auditoria:", lista_atendimentos)
        id_selecionado = int(selecionado.split(" ")[2])

        conn = obter_conexao()
        query = """
        SELECT s.Atendimentos_ID, COUNT(s.ID) as Qtd_Servicos, SUM(t.Valor) as Total
        FROM Servicos s
        JOIN TUSS t ON s.Cod_TUSS = t.CodTUSS
        WHERE s.Atendimentos_ID = ?
        GROUP BY s.Atendimentos_ID;
        """
        res = pd.read_sql_query(query, conn, params=(id_selecionado,))
        conn.close()

        if not res.empty:
            c1, c2 = st.columns(2)
            c1.metric("Componentes/Serviços Realizados", int(res['Qtd_Servicos'].iloc))
            c2.metric("Valor Líquido da Conta", f"R$ {res['Total'].iloc:.2f}")

            # Mostrar os detalhes dos exames incluídos no atendimento
            conn = obter_conexao()
            detalhes = pd.read_sql_query("""
                SELECT s.Data_Serv as "Data", s.Cod_TUSS as "Cód. TUSS", t.Descr as "Procedimento", t.Valor as "Valor (R$)"
                FROM Servicos s JOIN TUSS t ON s.Cod_TUSS = t.CodTUSS WHERE s.Atendimentos_ID = ?
            """, conn, params=(id_selecionado,))
            conn.close()
            st.dataframe(detalhes, use_container_width=True)

# CONSULTA 2: VALOR TOTAL DE ATENDIMENTOS DE UM PACIENTE ESPECÍFICO
with aba2:
    st.header("2. Faturamento Acumulado por Paciente")
    conn = obter_conexao()
    df_pacientes = pd.read_sql_query("SELECT id, Nome, CPF FROM Pacientes", conn)
    conn.close()

    lista_pacientes = [f"ID {row['id']} - {row['Nome']} (CPF: {row['CPF']})" for _, row in df_pacientes.iterrows()]

    if lista_pacientes:
        paciente_sel = st.selectbox("Selecione o Paciente Histórico:", lista_pacientes)
        id_pac = int(paciente_sel.split(" ")[1])

        conn = obter_conexao()
        query_pac = """
        SELECT p.Nome, COUNT(DISTINCT a.ID) as Total_Atendimentos, SUM(t.Valor) as Custos_Totais
        FROM Pacientes p
        JOIN Atendimentos a ON p.id = a.Pacientes_id
        JOIN Servicos s ON a.ID = s.Atendimentos_ID
        JOIN TUSS t ON s.Cod_TUSS = t.CodTUSS
        WHERE p.id = ?
        GROUP BY p.id, p.Nome;
        """
        res_pac = pd.read_sql_query(query_pac, conn, params=(id_pac,))
        conn.close()

        if not res_pac.empty:
            col_p1, col_p2 = st.columns(2)
            col_p1.metric("Atendimentos Clínicos Passados", int(res_pac['Total_Atendimentos'].iloc))
            col_p2.metric("Valor Consolidado Acumulado", f"R$ {res_pac['Custos_Totais'].iloc:.2f}")
        else:
            st.info("Este paciente não possui lançamentos de procedimentos faturados no sistema.")

# CONSULTA 3: SERVIÇOS PRESTADOS PARA UM CÓDIGO TUSS ESPECÍFICO
with aba3:
    st.header("3. Mecanismo de Busca por Código de Serviço TUSS")
    conn = obter_conexao()
    df_tuss_lista = pd.read_sql_query("SELECT CodTUSS, Descr FROM TUSS", conn)
    conn.close()

    opcoes_tuss = [f"{row['CodTUSS']} - {row['Descr']}" for _, row in df_tuss_lista.iterrows()]

    if opcoes_tuss:
        tuss_sel = st.selectbox("Escolha o Código TUSS para auditoria global:", opcoes_tuss)
        cod_tuss_alvo = tuss_sel.split(" ")

        conn = obter_conexao()
        query_tuss = """
        SELECT p.Nome AS "Nome Paciente", a.Data_atend AS "Data Atendimento", SUM(t.Valor) AS "Valor Total do Agrupamento"
        FROM Servicos s
        JOIN Atendimentos a ON s.Atendimentos_ID = a.ID
        JOIN Pacientes p ON a.Pacientes_id = p.id
        JOIN TUSS t ON s.Cod_TUSS = t.CodTUSS
        WHERE s.Cod_TUSS = ?
        GROUP BY p.id, p.Nome, a.ID, a.Data_atend;
        """
        df_res_tuss = pd.read_sql_query(query_tuss, conn, params=(cod_tuss_alvo,))
        conn.close()

        if not df_res_tuss.empty:
            st.dataframe(df_res_tuss, use_container_width=True)
        else:
            st.warning("Sem registos clínicos para este procedimento no banco de dados.")

# CONSULTA 4: SERVIÇOS PRESTADOS EM UMA DATA ESPECÍFICA
with aba4:
    st.header("4. Mecanismo de Busca Epidemiológico por Data")
    data_filtro = st.date_input("Escolha o dia de análise faturada:", value=datetime.strptime("2026-05-19", "%Y-%m-%d"))
    data_convertida = data_filtro.strftime("%Y-%m-%d")

    conn = obter_conexao()
    query_data = """
    SELECT s.Cod_TUSS AS "Código TUSS", t.Descr AS "Descrição do Serviço", p.Sexo AS "Sexo",
           COUNT(s.ID) AS "Quantidade Prestada", SUM(t.Valor) AS "Valor Total (R$)"
    FROM Servicos s
    JOIN TUSS t ON s.Cod_TUSS = t.CodTUSS
    JOIN Atendimentos a ON s.Atendimentos_ID = a.ID
    JOIN Pacientes p ON a.Pacientes_id = p.id
    WHERE s.Data_Serv = ?
    GROUP BY s.Cod_TUSS, t.Descr, p.Sexo;
    """
    df_res_data = pd.read_sql_query(query_data, conn, params=(data_convertida,))
    conn.close()

    if not df_res_data.empty:
        st.dataframe(df_res_data, use_container_width=True)
    else:
        st.info(f"Nenhuma atividade médica faturada no dia {data_filtro.strftime('%d/%m/%Y')}.")

# VALIDAÇÃO DE RESTRIÇÕES E INTEGRIDADE
with aba5:
    st.header("5. Auditoria de Integridade Referencial (Restrições MER)")
    st.info("🛡️ Este painel valida em tempo real o cumprimento das chaves estrangeiras (`FOREIGN KEY`) especificadas pela Engenharia.")

    st.markdown("**Regra do Negócio:** Não é permitido excluir um Atendimento da base caso existam Serviços atrelados financeiramente a ele.")

    if st.button("Simular Exclusão Proibida (Deletar Atendimento ID 1)"):
        conn = obter_conexao()
        cursor = conn.cursor()
        try:
            cursor.execute("DELETE FROM Atendimentos WHERE ID = 1;")
            conn.commit()
            st.error("Falha Crítica de Segurança: O atendimento foi apagado violando as regras!")
        except sqlite3.IntegrityError as erro:
            st.success(f"🔒 Ação Bloqueada com Sucesso! O banco barrou a operação protegendo a integridade dos dados: {erro}")
        finally:
            conn.close()